#!/usr/bin/env python3
"""Graph-memory CLI: append-only JSONL store queried via in-memory SQLite.

Stdlib only. The source of truth is a single append-only text file
(``memory/graph.jsonl``); every read loads it into an in-memory SQLite DB
(``nodes``/``edges`` tables) and every write appends one line under
``fcntl.flock`` with ``O_APPEND``.

Store path resolution order: ``--store`` flag > ``GRAPH_PATH`` env var >
``memory/graph.jsonl`` relative to the process cwd. This keeps the CLI usable
both from the repo root and from an isolated working directory.
"""

from __future__ import annotations

import argparse
import fcntl
import json
import os
import sqlite3
import sys
import time
import uuid

NODE_TYPES = ("lesson", "decision", "pattern", "gotcha")
REL_TYPES = ("applies_to", "related_to", "contradicts", "knows")
GENERATED_HEADER = (
    "<!-- GENERATED by memory/graph_memory.py — do not edit; "
    "source: memory/graph.jsonl -->"
)
AGENTS = ("orch", "patek", "lange", "philipe", "sohne", "gerald")


def _short_uuid() -> str:
    return uuid.uuid4().hex[:8]


def _now() -> int:
    return int(time.time())


def _display_name(agent: str) -> str:
    return agent.capitalize()


def default_store() -> str:
    env = os.environ.get("GRAPH_PATH")
    if env:
        return env
    return os.path.join(os.getcwd(), "memory", "graph.jsonl")


def append_record(store: str, record: dict) -> None:
    """Append one JSON line under an exclusive flock (O_APPEND)."""
    parent = os.path.dirname(os.path.abspath(store))
    if parent:
        os.makedirs(parent, exist_ok=True)
    line = json.dumps(record, ensure_ascii=False)
    fd = os.open(store, os.O_WRONLY | os.O_CREAT | os.O_APPEND, 0o644)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fcntl.flock(fh, fcntl.LOCK_EX)
            fh.write(line + "\n")
            fh.flush()
            fcntl.flock(fh, fcntl.LOCK_UN)
    except BaseException:
        try:
            os.close(fd)
        except OSError:
            pass
        raise


def load_db(store: str) -> sqlite3.Connection:
    """Load the JSONL store into an in-memory SQLite DB (nodes/edges)."""
    conn = sqlite3.connect(":memory:")
    conn.row_factory = sqlite3.Row
    conn.execute(
        "CREATE TABLE nodes (id TEXT PRIMARY KEY, type TEXT, agent TEXT, "
        "text TEXT, props TEXT, ts INTEGER)"
    )
    conn.execute("CREATE TABLE edges (src TEXT, dst TEXT, rel TEXT, ts INTEGER)")
    if os.path.exists(store):
        with open(store, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    rec = json.loads(line)
                except json.JSONDecodeError:
                    continue  # torn trailing line from a concurrent writer
                if rec.get("kind") == "node":
                    conn.execute(
                        "INSERT OR REPLACE INTO nodes VALUES (?,?,?,?,?,?)",
                        (
                            rec["id"],
                            rec.get("type", ""),
                            rec.get("agent", ""),
                            rec.get("text", ""),
                            json.dumps(rec.get("props", {})),
                            rec.get("ts", 0),
                        ),
                    )
                elif rec.get("kind") == "edge":
                    conn.execute(
                        "INSERT INTO edges VALUES (?,?,?,?)",
                        (
                            rec.get("src", ""),
                            rec.get("dst", ""),
                            rec.get("rel", ""),
                            rec.get("ts", 0),
                        ),
                    )
    return conn


def _adjacency(conn: sqlite3.Connection) -> dict[str, set[str]]:
    """Undirected adjacency map from the edges table."""
    adj: dict[str, set[str]] = {}
    for src, dst in conn.execute("SELECT src, dst FROM edges"):
        adj.setdefault(src, set()).add(dst)
        adj.setdefault(dst, set()).add(src)
    return adj


def _bfs_distances(adj: dict[str, set[str]], src: str) -> dict[str, int]:
    """Shortest-hop distances from src (BFS, undirected)."""
    dist = {src: 0}
    frontier = [src]
    while frontier:
        cur = frontier.pop(0)
        for nxt in adj.get(cur, ()):
            if nxt not in dist:
                dist[nxt] = dist[cur] + 1
                frontier.append(nxt)
    return dist


def _node_record(node_id, ntype, agent, text, props=None) -> dict:
    return {
        "kind": "node",
        "id": node_id,
        "type": ntype,
        "agent": agent,
        "text": text,
        "props": props or {},
        "ts": _now(),
    }


def _edge_record(src, dst, rel) -> dict:
    return {"kind": "edge", "src": src, "dst": dst, "rel": rel, "ts": _now()}


def _hub_id(agent: str) -> str:
    return f"agent:{agent}"


def _node_exists(conn: sqlite3.Connection, node_id: str) -> bool:
    return (
        conn.execute("SELECT 1 FROM nodes WHERE id = ?", (node_id,)).fetchone()
        is not None
    )


def _ensure_node(store, conn, record) -> None:
    """Append a node record (and mirror it into the DB) if the id is absent."""
    if not _node_exists(conn, record["id"]):
        append_record(store, record)
        conn.execute(
            "INSERT OR REPLACE INTO nodes VALUES (?,?,?,?,?,?)",
            (
                record["id"], record["type"], record["agent"],
                record["text"], json.dumps(record["props"]), record["ts"],
            ),
        )


def _superseded_ids(conn: sqlite3.Connection) -> set[str]:
    return {
        row[0]
        for row in conn.execute("SELECT dst FROM edges WHERE rel = 'supersedes'")
    }


def _add_node(store, conn, text, agent, ntype, applies_to=(), related=()):
    """Append one memory node plus its knows/applies_to/related_to edges."""
    hub = _hub_id(agent)
    _ensure_node(store, conn, _node_record(
        hub, "agent", agent, f"{_display_name(agent)} hub"))

    node_id = f"{ntype}:{agent}:{_short_uuid()}"
    append_record(store, _node_record(node_id, ntype, agent, text))
    append_record(store, _edge_record(hub, node_id, "knows"))

    for topic in applies_to:
        tid = f"topic:{topic}"
        _ensure_node(store, conn, _node_record(tid, "topic", "", topic))
        append_record(store, _edge_record(node_id, tid, "applies_to"))

    for rel_id in related:
        append_record(store, _edge_record(node_id, rel_id, "related_to"))

    return node_id


def _with_db(args, fn):
    conn = load_db(args.store)
    try:
        return fn(conn, args)
    finally:
        conn.close()


def cmd_add(args) -> int:
    return _with_db(args, _cmd_add)


def _cmd_add(conn, args) -> int:
    node_id = _add_node(
        args.store, conn, args.text, args.agent, args.type,
        applies_to=args.applies_to, related=args.related,
    )
    print(node_id)
    return 0


def cmd_link(args) -> int:
    append_record(args.store, _edge_record(args.src, args.dst, args.rel))
    print(f"{args.src} -[{args.rel}]-> {args.dst}")
    return 0


def cmd_supersede(args) -> int:
    return _with_db(args, _cmd_supersede)


def _find_nodes(conn, ref: str):
    """Candidate node ids for a reference: exact id, id suffix, or text."""
    if _node_exists(conn, ref):
        return [ref]
    rows = [r["id"] for r in conn.execute(
        "SELECT id FROM nodes WHERE id LIKE ?", (f"%:{ref}",))]
    if rows:
        return rows
    return [r["id"] for r in conn.execute(
        "SELECT id FROM nodes WHERE text = ?", (ref,))]


def _node_agent(node_id: str) -> str:
    parts = node_id.split(":")
    return parts[1] if len(parts) > 1 else ""


def _cmd_supersede(conn, args) -> int:
    old_cands = _find_nodes(conn, args.old)
    new_cands = _find_nodes(conn, args.new)

    # Text form: NEW names no existing node -> create the replacement node.
    if not new_cands:
        # Pick the old node, preferring --agent's own nodes.
        if args.agent:
            owned = [i for i in old_cands if _node_agent(i) == args.agent]
            old_cands = owned or old_cands
        if len(old_cands) != 1:
            print(f"supersede: {args.old!r} matched {len(old_cands)} nodes; "
                  "pass an exact id", file=sys.stderr)
            return 1
        old_id = old_cands[0]
        agent = args.agent or _node_agent(old_id)
        new_id = _add_node(args.store, conn, args.new, agent, args.type)
        append_record(args.store, _edge_record(new_id, old_id, "supersedes"))
        print(new_id)
        return 0

    # Id form: supersede OLD_ID NEW_ID -> bare supersedes edge.
    old_id = old_cands[0] if len(old_cands) == 1 else args.old
    new_id = new_cands[0] if len(new_cands) == 1 else args.new
    append_record(args.store, _edge_record(new_id, old_id, "supersedes"))
    print(f"{new_id} -[supersedes]-> {old_id}")
    return 0


def cmd_query(args) -> int:
    return _with_db(args, _cmd_query)


def _cmd_query(conn, args) -> int:
    superseded = _superseded_ids(conn)
    like = f"%{args.keyword}%"
    rows = conn.execute(
        "SELECT id, type, text FROM nodes WHERE text LIKE ?", (like,)
    ).fetchall()

    # Rank by proximity to the agent hub: 1-hop (known) neighbours first,
    # then by graph distance; unreachable nodes last.
    adj = _adjacency(conn)
    dist = _bfs_distances(adj, _hub_id(args.agent))
    inf = float("inf")

    def sort_key(row):
        d = dist.get(row["id"], inf)
        return (0 if d == 1 else 1, d)

    hits = [r for r in rows if r["id"] not in superseded]
    hits.sort(key=sort_key)
    for row in hits[: max(args.k, 0)]:
        print(f"{row['id']} [{row['type']}] {row['text']}")
    return 0


def cmd_path(args) -> int:
    return _with_db(args, _cmd_path)


def _cmd_path(conn, args) -> int:
    a_cands, b_cands = _find_nodes(conn, args.a), _find_nodes(conn, args.b)
    a = a_cands[0] if len(a_cands) == 1 else args.a
    b = b_cands[0] if len(b_cands) == 1 else args.b
    adj = _adjacency(conn)
    prev = {a: None}
    frontier = [a]
    while frontier and b not in prev:
        cur = frontier.pop(0)
        for nxt in adj.get(cur, ()):
            if nxt not in prev:
                prev[nxt] = cur
                if nxt == b:
                    break
                frontier.append(nxt)
    if b not in prev:
        print(f"no path: {args.a} ~ {args.b}")
        return 1
    chain = []
    node = b
    while node is not None:
        chain.append(node)
        node = prev[node]
    chain.reverse()
    print(" -> ".join(chain))
    return 0


def cmd_export(args) -> int:
    return _with_db(args, _cmd_export)


def _cmd_export(conn, args) -> int:
    superseded = _superseded_ids(conn)
    outdir = args.dir
    os.makedirs(outdir, exist_ok=True)

    hubs = conn.execute(
        "SELECT id, agent FROM nodes WHERE type = 'agent' ORDER BY agent"
    ).fetchall()
    for hub in hubs:
        agent = hub["agent"]
        rows = conn.execute(
            "SELECT n.id, n.type, n.text FROM edges e "
            "JOIN nodes n ON n.id = e.dst "
            "WHERE e.src = ? AND e.rel = 'knows' ORDER BY n.ts, n.id",
            (hub["id"],),
        ).fetchall()
        grouped: dict[str, list[str]] = {}
        for row in rows:
            if row["id"] in superseded:
                continue
            grouped.setdefault(row["type"], []).append(
                f"- `{row['id']}` {row['text']}"
            )

        lines = [GENERATED_HEADER, "", f"# {_display_name(agent)} - Memory", ""]
        if not grouped:
            lines.append("_No memories recorded yet._")
        else:
            for ntype in NODE_TYPES:
                if ntype in grouped:
                    lines += [f"## {ntype.capitalize()}s", ""]
                    lines += grouped[ntype]
                    lines.append("")
            for ntype in sorted(set(grouped) - set(NODE_TYPES)):
                lines += [f"## {ntype.capitalize()}s", ""]
                lines += grouped[ntype]
                lines.append("")

        path = os.path.join(outdir, agent, "memory.md")
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write("\n".join(lines).rstrip("\n") + "\n")
        print(path)
    return 0


def cmd_seed(args) -> int:
    """Seed the six agent hub nodes (idempotent)."""
    return _with_db(args, _cmd_seed)


def _cmd_seed(conn, args) -> int:
    for name in AGENTS:
        _ensure_node(args.store, conn, _node_record(
            _hub_id(name), "agent", name, f"{_display_name(name)} hub"))
    print(f"seeded {len(AGENTS)} agent hubs -> {args.store}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="graph_memory",
        description="Graph-memory CLI over an append-only JSONL store.",
    )
    p.add_argument("--store", default=None,
                   help="JSONL store path (default: $GRAPH_PATH or "
                        "./memory/graph.jsonl)")
    sub = p.add_subparsers(dest="cmd", required=True)

    sp = sub.add_parser("add", help="add a knowledge node")
    sp.add_argument("text", metavar="TEXT")
    sp.add_argument("--agent", required=True)
    sp.add_argument("--type", required=True, choices=NODE_TYPES)
    sp.add_argument("--applies-to", action="append", default=[],
                    metavar="K", help="topic key (repeatable)")
    sp.add_argument("--related", action="append", default=[],
                    metavar="ID", help="related node id (repeatable)")
    sp.set_defaults(func=cmd_add)

    sp = sub.add_parser("link", help="add an edge")
    sp.add_argument("src", metavar="SRC")
    sp.add_argument("dst", metavar="DST")
    sp.add_argument("--rel", required=True, choices=REL_TYPES)
    sp.set_defaults(func=cmd_link)

    sp = sub.add_parser(
        "supersede",
        help="mark an old node superseded (OLD_ID NEW_ID, or "
             "OLD_TEXT NEW_TEXT --agent A [--type T])",
    )
    sp.add_argument("old", metavar="OLD_ID|OLD_TEXT",
                    help="old node id (or exact text)")
    sp.add_argument("new", metavar="NEW_ID|NEW_TEXT",
                    help="new node id, or text for the replacement node")
    sp.add_argument("--agent", help="owning agent (text form)")
    sp.add_argument("--type", choices=NODE_TYPES, default="lesson",
                    help="type of the replacement node (text form)")
    sp.set_defaults(func=cmd_supersede)

    sp = sub.add_parser("query", help="keyword search ranked by hub proximity")
    sp.add_argument("keyword", metavar="KEYWORD")
    sp.add_argument("--agent", required=True)
    sp.add_argument("--k", type=int, default=5)
    sp.set_defaults(func=cmd_query)

    sp = sub.add_parser("path", help="shortest path between two node ids")
    sp.add_argument("a", metavar="A")
    sp.add_argument("b", metavar="B")
    sp.set_defaults(func=cmd_path)

    sp = sub.add_parser("export", help="regenerate per-agent memory.md files")
    sp.add_argument("--dir", default="agents",
                    help="output directory (default: agents)")
    sp.set_defaults(func=cmd_export)

    sp = sub.add_parser("seed", help="seed the six agent hub nodes")
    sp.set_defaults(func=cmd_seed)

    return p


def main(argv=None) -> int:
    args = build_parser().parse_args(argv)
    if args.store is None:
        args.store = default_store()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
